/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "surface-variant": "#e2e8f0",
              "on-error-container": "#93000a",
              "surface-container-highest": "#cbd5e1",
              "on-error": "#ffffff",
              "on-tertiary-container": "#f8fafc",
              "secondary-fixed-dim": "#94a3b8",
              "primary-fixed": "#a5b4fc",
              "inverse-on-surface": "#f1f5f9",
              "tertiary": "#0ea5e9",
              "tertiary-fixed-dim": "#7dd3fc",
              "on-tertiary-fixed-variant": "#0369a1",
              "background": "#f8fafc",
              "on-primary": "#ffffff",
              "primary-fixed-dim": "#818cf8",
              "on-surface": "#0f172a",
              "outline": "#64748b",
              "on-primary-fixed-variant": "#3730a3",
              "surface-container-lowest": "#ffffff",
              "on-tertiary": "#ffffff",
              "on-surface-variant": "#475569",
              "surface-container-low": "#f1f5f9",
              "inverse-surface": "#1e293b",
              "surface-container": "#e2e8f0",
              "on-secondary-fixed": "#0f172a",
              "on-background": "#0f172a",
              "secondary": "#475569",
              "primary": "#4f46e5",
              "secondary-container": "#f1f5f9",
              "secondary-fixed": "#e2e8f0",
              "on-secondary-container": "#1e293b",
              "surface-bright": "#f8fafc",
              "surface-tint": "#4338ca",
              "primary-container": "#e0e7ff",
              "surface-dim": "#e2e8f0",
              "on-primary-fixed": "#1e1b4b",
              "on-primary-container": "#312e81",
              "error": "#dc2626",
              "tertiary-fixed": "#bae6fd",
              "inverse-primary": "#818cf8",
              "on-secondary": "#ffffff",
              "outline-variant": "#cbd5e1",
              "on-secondary-fixed-variant": "#334155",
              "surface-container-high": "#cbd5e1",
              "error-container": "#fecaca",
              "surface": "#f8fafc",
              "tertiary-container": "#e0f2fe",
              "on-tertiary-fixed": "#0c4a6e"
          },
          "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
          },
          "spacing": {
              "container-max": "1200px",
              "gutter": "24px",
              "margin-mobile": "16px",
              "margin-desktop": "40px",
              "unit": "8px"
          },
          "fontFamily": {
              "headline-lg": ["Geist", "sans-serif"],
              "headline-md": ["Geist", "sans-serif"],
              "body-lg": ["Geist", "sans-serif"],
              "headline-lg-mobile": ["Geist", "sans-serif"],
              "label-sm": ["Geist", "sans-serif"],
              "display": ["Geist", "sans-serif"],
              "body-md": ["Geist", "sans-serif"],
              "label-md": ["Geist", "sans-serif"]
          },
          "fontSize": {
              "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
              "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "display": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}]
          }
      }
  },
  plugins: [],
}
